dist: trusty
language: node_js
node_js: lts/*
cache:
  bundler: true
  pip: true
  npm: true
  directories:
  - ~/.cache
before_install:
- pyenv local 3.6
install:
- travis_retry gem install s3_website -v 3.4.0
- travis_retry pip install awscli --upgrade --user
- travis_retry npm ci
- travis_retry cypress install
- travis_retry npm install codecov
script:
- npm run build
- npx nyc --reporter=lcov npm run test:coverage -- --runInBand
- npm run start &
- wait-on http://localhost:8080
- CODE_COVERAGE=true && $(npm bin)/cypress run --config video=false --record
- npx codecov
after_success:
- ./s3_deploy.sh
after_script:
- bash <(curl -s https://codecov.io/bash)
